### ISSUE TITLE
Allow "Git Push" when Branching is disabled

### ISSUE THREAD

**Issue by wegotoeleven** [grahampugh/munki-do#19]
Allow users to commit to the master branch when Branching is disabled ( -e DOCKER_MUNKIDO_GIT_BRANCHING="" \ in the Docker Run command).

**Comment by grahampugh** [comment]
That should work, if ssh is set up properly. Can you give an example?

**Comment by grahampugh** [comment]
On testing, this indeed isn't working. Looking into it now.

**Comment by grahampugh** [comment]
This seems to work but there appears some fragility as to whether the `git push` command works, which may be because no `git pull` has been performed to ensure a good repo state. 

I've added the "Update view (git pull)" button for all git-enabled settings (not just when branching is enabled), which might improve things. 

I've also added a lot more logging so it's more obvious if it hasn't worked, and why. FYI, I've avoided setting a `git pull` with every view refresh, as it's a performance hit.
